config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
      resources :posts
      resources :reported_posts
      resources :users

      root to: "posts#index"
    end
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :post_comments
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :reported_posts

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'report/:id', to: 'reported_posts#report', as: 'report'


end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :post_comments, dependent: :destroy
    has_many :reported_posts, dependent: :destroy
    
    validates :title, presence: true, length: {minimum: 5}
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    def index
      super
      puts "hello"
      @resources = Post.
        page(params[:page]).
        per(10)
    end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :current_user
    @error_messages = ""
    @info_messages = nil
    def current_user
        if session[:user_id]
            begin
                @current_user = User.find(session[:user_id])
            rescue ActiveRecord::RecordNotFound => e
                @current_user = nil
                session[:user_id] = nil
            end
        else
            @current_user = nil
            redirect_to login_path
        end
    end
    def index
        if(session[:user_id] == nil)
            redirect_to login_path
        else
            @current_user = User.find(session[:user_id])
            @posts = Post.all
        end
    end

    def show
        @post = Post.find(params[:id])
    
    end

    def new
        @post = Post.new
    end

    def create
        # render plain: params[:post].inspect
        @post = Post.new(post_params)
        @post.user_id = @current_user.id

        if(@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end

    def edit
        @post = Post.find(params[:id])
        if(@post.user_id != @current_user.id)
            redirect_to posts_path
        end
    end

    def update
        @post = Post.find(params[:id])

        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    

    private def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h2>Edit Post</h1>
<script>
     function autoheight() {
        if (!$("#ta").prop('scrollTop')) {
            do {
                var b = $("#ta").prop('scrollHeight');
                var h = $("#ta").height();
                $("#ta").height(h - 5);
            }
            while (b && (b != $("#ta").prop('scrollHeight')));
        };
        $("#ta").height($("#ta").prop('scrollHeight') + 10);
    }
</script>


<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, :class => "form-control") %>
    </p>

    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, :class => "form-control", id: "ta", onkeyup: "autoheight()") %>
    </p>

    <p>
        <%= f.submit(:class => "btn btn-success") %>
    </p>
<% end %>

<script>
    autoheight($("#ta"));
</script>

app/views/posts/index.html.erb
<h2>Blog Posts</h2>
<br>
<% @posts.each do |post| %>
    <div class="card bg-light">
        <div class="card-body">
            <h4 class="card-title"><%= post.title %></h4>
            <p card="card-text" style="font-weight: bold">By <%= User.find(post.user_id).name %></p>
            <p class="card-text"><%= simple_format(post.body) %></p>
            <%= link_to "Read More", post_path(post), :class=> "btn btn-outline-dark" %>
        </div>
    </div>
    <br>
<% end %>

app/views/posts/new.html.erb
<h2>Add Post</h2>

<script>
    function autoheight() {
        if (!$("#ta").prop('scrollTop')) {
            do {
                var b = $("#ta").prop('scrollHeight');
                var h = $("#ta").height();
                $("#ta").height(h - 5);
            }
            while (b && (b != $("#ta").prop('scrollHeight')));
        };
        $("#ta").height($("#ta").prop('scrollHeight') + 10);
    }
</script>

<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, :class => "form-control") %>
    </p>

    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, :class => "form-control", id: "ta", onkeyup: 'autoheight()' ) %>
    </p>

    <p>
        <%= f.submit(:class => "btn btn-success") %>
    </p>

    
<% end %>

app/views/posts/show.html.erb
<script>
    function autoheight() {
        if (!$("#ta").prop('scrollTop')) {
            do {
                var b = $("#ta").prop('scrollHeight');
                var h = $("#ta").height();
                $("#ta").height(h - 5);
            }
            while (b && (b != $("#ta").prop('scrollHeight')));
        };
        $("#ta").height($("#ta").prop('scrollHeight') + 10);
    }
</script>

<script>
    #inner_remaining {
        background-color: #DDDDDD;    
    
        position: absolute;
        top: 100px;
        bottom: 0;
        width: 100%; 
    }
</script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<% if notice %>
    <div class="alert alert-info"><%= notice %></div>
<% end %>
<h2><%= @post.title %></h2>
<p><%= simple_format(@post.body) %></p>
<h6 style="font-weight:bold">-<%= User.find(@post.user_id).name %></h6>
<hr>
<div>
    <% if @post.user_id == @current_user.id %>
        <%= link_to "Edit", edit_post_path(@post), :class => "btn btn-outline-primary", :style => "margin-right:5px" %>
        <button type="button" style="float: right" class="btn btn-outline-danger" data-toggle="modal" data-target="#exampleModal">
            Delete
        </button>

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    This action cannot be undone.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <%= link_to"Confirm", post_path(@post), method: :delete, :class => "btn btn-danger" %>
                </div>
                </div>
            </div>
        </div>
    <% else %>
        <%= link_to "Report", report_path([@post]), :class => "btn btn-outline-dark"%>
    <% end %>
</div>
<br>
<h5>Comments</h5>
<div>
    <%= form_for([@post, @post.post_comments.build]) do |f| %>
        <p>
            <%= f.text_area(:body, :class => "form-control", id: "ta", onkeyup: 'autoheight()', placeholder: 'Add comment...' ) %>
        </p>
        <p>
            <%= f.submit("Post", :class => "btn btn-primary", style: "float:right") %>
        </p>
    <% end %>
    <br>
    <br>
    <div id="inner_remaining">
        <div class="card" style="height: 100%; overflow: auto;">
            <% @post.post_comments.each.with_index do |comment, i| %>
                <% if comment.id != nil %>
                    <div class="card-body" style="font-size: 20px; padding: 8px; padding-left: 10px; padding-right: 10px">
                        <%= comment.body %><br>
                        <b style="font-size: 15px">-<%= User.find(comment.user_id).name %></b>
                        <% if comment.user_id == @current_user.id %>
                            <%= link_to "X", [comment.post, comment], method: :delete, :class => "btn btn-danger", style: "float: right; font-size: 15px"%>
                        <% end %>
                    </div>

                    <% if i != @post.post_comments.length-1 %>
                        <hr style="margin: 5px">
                    <% end %>
                <% end %>
            <% end %>
        </div>
    </div>
</div>