config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
      resources :posts
      resources :reported_posts
      resources :users

      root to: "posts#index"
    end
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :post_comments
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :reported_posts

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'report/:id', to: 'reported_posts#report', as: 'report'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js' %>
    <%= javascript_include_tag 'hhttps://use.fontawesome.com/releases/v5.6.3/css/all.css' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/js/bootstrap.min.js' %>
    <%# <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if @current_user != nil %>
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
      <a class="navbar-brand"><img src="/images/icon.png" alt="logo" width="45" height="45" ></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", home_path, :class => "nav-link", :style=>"font-weight: bold" %><span class="sr-only">(current)</span>
          </li>        
        </ul>

        <ul class="navbar-nav">
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= @current_user.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Edit Account", edit_user_path(@current_user), :class => "dropdown-item" %>
              <%= link_to "Logout", logout_path, :class => "dropdown-item" %>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <%= link_to "Create Post", new_post_path, :class => "btn btn-outline-success my-2 my-sm-0" %>
        </form>
      </div>
    </nav>
  <% end %>
    <br><br><br><br>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>